name: Build and Upload

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/*'
      - 'include/*'
      - 'test/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WIFI_SSID: ${{ secrets.WIFI_SSID }}
  WIFI_PASS: ${{ secrets.WIFI_PASS }}
  MQTT_USER: ${{ secrets.MQTT_USER }}
  MQTT_PASS: ${{ secrets.MQTT_PASS }}
  MQTT_SERV: ${{ secrets.MQTT_SERV }}
  ESP32_ID1: ${{ secrets.ESP32_ID1 }}
  ESP32_IP1: ${{ secrets.ESP32_IP1 }}

jobs:
  build:
    name: "Build-Test-Upload"
    runs-on: self-hosted    
    steps:    
      - uses: actions/checkout@v3
      - name: "unit tests"
        run: |
          pio test -vv
        shell: bash
      - name: "build and copy firmware to update server"
        run: |
          pio run --target upload --environment nodemcu-32s
          echo "VERSION=${VERSION}"
          cp .pio/build/nodemcu-32s/firmware.bin /home/runner/firmware/update/firmware-${VERSION}.bin
          echo "Firmware.bin compilado y copiado a /home/runner/firmware/update"